name: opswrapper
dependencies:
  - python >= 3.7
  - numpy
  - toml
  - xarray
  # Testing
  - ipython
  - line_profiler
  - yapf
  - pytest
  # Needed for examples
  - matplotlib
  # Documentation
  - sphinx
  # Development install
  - pip
  - pip:
    - "-e ."
