{% set data = load_setup_py_data() %}

package:
  name: opswrapper
  version: {{ data.get('version') }}

source:
  path: ".."

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python>=3.7.0
    - numpy
    - toml
    - xarray

test:
  imports:
    - opswrapper
    - opswrapper.analysis
    - opswrapper.config
    - opswrapper.element
    - opswrapper.integration
    - opswrapper.material
    - opswrapper.output
    - opswrapper.section
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}
