{% set data = load_setup_py_data() %}

package:
  name: opswrapper
  version: {{ data.get('version') }}

source:
  git_url: ".."

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps -vv .

requirements:
  host:
    - python
    - pip
  run:
    - python>=3.9.0
    - numpy
    - tomli  # [py<3.11]
    - xarray

test:
  imports:
    - opswrapper
    - opswrapper.algorithm
    - opswrapper.analysis
    - opswrapper.backports
    - opswrapper.base
    - opswrapper.config
    - opswrapper.constraints
    - opswrapper.element
    - opswrapper.formatting
    - opswrapper.integration
    - opswrapper.integrator
    - opswrapper.material
    - opswrapper.model
    - opswrapper.output
    - opswrapper.section
    - opswrapper.test
    - opswrapper.uniaxialmaterialanalysis
    - opswrapper.utils
  requires:
    - pytest
  source_files:
    - test
  commands:
    - pytest

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}
